# Generated by Django 4.1.4 on 2023-11-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
